### ISSUE TITLE
卡在了验证整合是否成功

### ISSUE THREAD

**Issue by ellisfan** [toadgg/lumen-api-starter#4]
直接访问http://localhost:8000/api/users/~me

{
  "message": "Fatal error: Call to undefined method Closure::authenticate()",
  "status_code": 500,
}

用户鉴权http://localhost:8000/oauth/access_token，发送post请求

{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."
}

**Comment by toadgg** [comment]
Fatal error: Call to undefined method Closure::authenticate()
这个错误，我暂时没有思路，因为在我的环境里面是没问题的，确认一下“composer update”执行过程中没有报错吧。

用户鉴权http://localhost:8000/oauth/access_token，发送post请求这个问题
你可以参考一下这个图片
![postman-oauth](http://image.bibihub.com/php/postman-oauth.png)
提交post请求需要设置Content-Type   application/json;charset=UTF-8
然后在请求的body中，设置参数，那个错误提示很明显，你没有设置“grant_type”这个参数，如果你设置了，可能方式不对，你可以在网上查查“Content-Type”的作用。
